/*
[#1 조건에 부합하는 중고거래 댓글 조회하기]
a와 b는 alias로 별명임
뒤에 정렬은 각각 1차 정렬, 2차정렬임
+ 문제에서 요구하는 컬럼이 두 테이블 중 어느 곳에 소속되어있는지 명확히 파악하는 것 중요
 */
SELECT a.TITLE, a.BOARD_ID, b.REPLY_ID, b.WRITER_ID, b.CONTENTS, TO_CHAR(b.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD a JOIN USED_GOODS_REPLY b
ON a.BOARD_ID = b.BOARD_ID
WHERE TO_CHAR(a.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY b.CREATED_DATE, a.TITLE;

/*
[#2 과일로 만든 아이스크림 고르기]
WHERE 절 사용 시 조건이 여러 개일 경우 AND로 연결해주기
 */
SELECT a.FLAVOR
FROM FIRST_HALF a JOIN ICECREAM_INFO b
ON a.FLAVOR = b.FLAVOR
WHERE a.TOTAL_ORDER > 3000 AND b.INGREDIENT_TYPE = 'fruit_based'
ORDER BY a.TOTAL_ORDER DESC;

/*
[#3 흉부외과 또는 일반외과 의사 목록 출력하기]
IN 문법: WHERE 절에서 여러 개의 값 중 하나라도 일치하는지를 확인할 때 사용하는 조건식
 */
SELECT DR_NAME, DR_ID, MCDP_CD, TO_CHAR(HIRE_YMD, 'YYYY-MM-DD') AS HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD IN ('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME;

/*
[#4 12세 이하인 여자 환자 목록 출력하기]
풀이 1. NVL함수(표현식이 NULL인지 검사한 후, NULL이면 NULL값을 대체값으로 바꿔주는 함수)
- NVL(표현식, 대체값)
 */
SELECT PT_NAME, PT_NO, GEND_CD, AGE, NVL(TLNO, 'NONE')
FROM PATIENT
WHERE AGE < 13 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME;

SELECT PT_NAME, PT_NO, GEND_CD, AGE, CASE WHEN TLNO IS NULL THEN 'NONE' ELSE TLNO END AS TLNO FROM PATIENT WHERE AGE <= 12 AND GEND_CD = 'W' ORDER BY AGE DESC, PT_NAME;
SELECT PT_NAME, PT_NO, GEND_CD, AGE, COALESCE(TLNO, 'NONE') AS TLNO FROM PATIENT WHERE AGE <= 12 AND GEND_CD = 'W' ORDER BY AGE DESC, PT_NAME;

-- [#5 인기있는 아이스크림]
SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID;

-- [#6 조건에 맞는 도서 리스트 출력하기]
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
WHERE TO_CHAR(PUBLISHED_DATE, 'YYYY') = '2021' AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;
